### ISSUE TITLE
sheet 9 - Hint

### ISSUE THREAD

**Issue by mhubii** [DerThorsten/mlcv#2]
Is there a mistake in the current sheet 9, where the hint tells us the dimensions of the matrices for the derivative dl/dW2? They do not match somehow. It should read Shape=(nHidden, nInput) instead of Shape=(nHidden, nClasses).

**Comment by DerThorsten** [comment]
Hubs, I guess your right!
Feel free to read more at
http://cs231n.github.io/neural-networks-case-study/

**Comment by mhubii** [comment]
Thx for the page :)

There is one more thing. Where we are asked to derive dl/dW1. The partial derivative of the ReLu l(o1 > 0), should obey the condition l(z1 > 0) instead.
